name: NoWeather
version: ${version}
main: me.seyviyer.noweather.NoWeather
api-version: '1.18'
authors: [ seyviyer ]

commands:
  noweather:
    description: Allows you to add or remove world to disable weather.
    default: op
permissions:
  noweather.admin:
    description: Allows you to use /noweather command.
